language: generic

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - nvidia-cuda-dev
          sources: &sources
            - ubuntu-toolchain-r-test
before_script:
  - mkdir -p build
  - cd build 
  - ../code-generator.py --enable-cuda
script:
  - cd build 
  - make
